config/routes.rb
Rails.application.routes.draw do
  resources :questionnaires
  resources :orderdetails
  resources :storages
  resources :books
  resources :orders
  resources :stores
  devise_for :users
  resources :customers
  #get 'home/index'
  get 'home/user'
  get 'home/dataview'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/orderdetail.rb
class Orderdetail < ApplicationRecord
	has_many :books
	has_many :orders
end

app/controllers/orderdetails_controller.rb
class OrderdetailsController < ApplicationController
  before_action :set_orderdetail, only: %i[ show edit update destroy ]

  # GET /orderdetails or /orderdetails.json
  def index
    @orderdetails = Orderdetail.all
  end

  # GET /orderdetails/1 or /orderdetails/1.json
  def show
  end

  # GET /orderdetails/new
  def new
    @orderdetail = Orderdetail.new
  end

  # GET /orderdetails/1/edit
  def edit
  end

  # POST /orderdetails or /orderdetails.json
  def create
    @orderdetail = Orderdetail.new(orderdetail_params)

    respond_to do |format|
      if @orderdetail.save
        format.html { redirect_to orderdetail_url(@orderdetail), notice: "Orderdetail was successfully created." }
        format.json { render :show, status: :created, location: @orderdetail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @orderdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orderdetails/1 or /orderdetails/1.json
  def update
    respond_to do |format|
      if @orderdetail.update(orderdetail_params)
        format.html { redirect_to orderdetail_url(@orderdetail), notice: "Orderdetail was successfully updated." }
        format.json { render :show, status: :ok, location: @orderdetail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @orderdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orderdetails/1 or /orderdetails/1.json
  def destroy
    @orderdetail.destroy

    respond_to do |format|
      format.html { redirect_to orderdetails_url, notice: "Orderdetail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orderdetail
      @orderdetail = Orderdetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def orderdetail_params
      params.require(:orderdetail).permit(:detnum, :amount, :price)
    end
end

app/helpers/orderdetails_helper.rb
module OrderdetailsHelper
end

app/views/orderdetails/_form.html.erb
<%= form_with(model: orderdetail) do |form| %>
  <% if orderdetail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(orderdetail.errors.count, "error") %> prohibited this orderdetail from being saved:</h2>

      <ul>
        <% orderdetail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :detnum, style: "display: block" %>
    <%= form.number_field :detnum %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orderdetails/_orderdetail.html.erb
<div id="<%= dom_id orderdetail %>">
  <p>
    <strong>Detnum:</strong>
    <%= orderdetail.detnum %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= orderdetail.amount %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= orderdetail.price %>
  </p>

</div>

app/views/orderdetails/edit.html.erb
<h1>Editing orderdetail</h1>

<%= render "form", orderdetail: @orderdetail %>

<br>

<div>
  <%= link_to "Show this orderdetail", @orderdetail %> |
  <%= link_to "Back to orderdetails", orderdetails_path %>
</div>

app/views/orderdetails/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orderdetails</h1>

<div id="orderdetails">
  <% @orderdetails.each do |orderdetail| %>
    <%= render orderdetail %>
    <p>
      <%= link_to "Show this orderdetail", orderdetail %>
    </p>
  <% end %>
</div>

<%= link_to "New orderdetail", new_orderdetail_path %>

app/views/orderdetails/new.html.erb
<h1>New orderdetail</h1>

<%= render "form", orderdetail: @orderdetail %>

<br>

<div>
  <%= link_to "Back to orderdetails", orderdetails_path %>
</div>

app/views/orderdetails/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @orderdetail %>

<div>
  <%= link_to "Edit this orderdetail", edit_orderdetail_path(@orderdetail) %> |
  <%= link_to "Back to orderdetails", orderdetails_path %>

  <%= button_to "Destroy this orderdetail", @orderdetail, method: :delete %>
</div>