config/routes.rb
Rails.application.routes.draw do
  resources :questionnaires
  resources :orderdetails
  resources :storages
  resources :books
  resources :orders
  resources :stores
  devise_for :users
  resources :customers
  #get 'home/index'
  get 'home/user'
  get 'home/dataview'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/store.rb
class Store < ApplicationRecord
	has_many :orders
	has_many :storages
	
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]

  # GET /stores or /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to store_url(@store), notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to store_url(@store), notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:storeid, :storename, :mail, :address)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div  class="mb-3">
    <%= form.number_field :storeid , class:"form-control", placeholder:"店舗ID" %>
  </div>

  <div  class="mb-3">
    <%= form.text_field :storename , class:"form-control", placeholder:"店舗名"%>
  </div>

  <div  class="mb-3">

    <%= form.text_field :mail , class:"form-control", placeholder:"メールアドレス" %>
  </div>

  <div  class="mb-3">

    <%= form.text_area :address , class:"form-control", placeholder:"住所" %>
  </div>

  <div>
    <%= form.submit "登録" ,class:"btn btn-dark"%>
  </div>
<% end %>

app/views/stores/_store.html.erb
<div id="<%= dom_id store %>">
  <tr>
  <td>
    <strong><%= store.storeid %></strong>
  </td>
  
  <td>
    <%= store.storename %>
  </td>

  <td>
    <%= store.mail %>
  </td>

  <td>
    <%= store.address %>
  </td>

  <td>
    <%= link_to "詳細", store %>
  </td>
  </tr>

</div>

app/views/stores/edit.html.erb
<h1>店舗データ更新</h1>
<br>

<%= render "form", store: @store %>

<br>

<div style="margin: auto;text-align: right;">
  <div style="margin-left:auto;margin-right: 0;display: inline-block;">
    <%= link_to "表示", @store, class:"btn btn-secondary" %>
  </div>
  <div style="margin-left:0;margin-right: auto;display: inline-block;">
    <%= link_to "戻る", stores_path, class:"btn btn-secondary" %>
  </div>
</div>

app/views/stores/index.html.erb
<h1>店舗データ</h1>

<table class="table table-hover table-striped table-bordered">
  <thead class="table-dark">
    <th>店舗ID</th>
    <th>店舗名</th>
    <th>メールアドレス</th>
    <th>住所</th>
    <th>詳細</th>
  </thead>

  <tbody>
    <div id="stores">
      <% @stores.each do |store| %>
      <%= render store %>
      <% end %>
    </div>
  </tbody>
</table>
<!--
<%= link_to "New store", new_store_path %>
-->

app/views/stores/new.html.erb
<h1>店舗データ新規登録</h1>
<br>

<%= render "form", store: @store %>

<br>

<div style="margin: auto;text-align: right;">
  <%= link_to "戻る", stores_path, class:"btn btn-secondary"  %>
</div>

app/views/stores/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <h1 class="display-4"><%= @store.storename %></h1>
  <p class="lead">
    住所: <%= @store.address %> <br>
    メールアドレス: <%= @store.mail %>
  </p>
  <p class="lead">
    <div style="margin-left:auto;margin-right: 0;display: inline-block;">
    <%= link_to "更新", edit_store_path(@store), class:"btn btn-dark"%>
    </div>
    <div style="margin-left:0;margin-right: auto;display: inline-block;">
    <%= button_to "削除", @store, method: :delete, class:"btn btn-danger" %>
    </div>
  </p>
  <hr class="my-4">
</div>

<div style="margin: auto;text-align: right;">
  <%= link_to "戻る", stores_path, class:"btn btn-secondary" %>
</div>