config/routes.rb
Rails.application.routes.draw do
  resources :questionnaires
  resources :orderdetails
  resources :storages
  resources :books
  resources :orders
  resources :stores
  devise_for :users
  resources :customers
  #get 'home/index'
  get 'home/user'
  get 'home/dataview'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
	has_many :storages
	has_many :orderdetails
	has_rich_text :body
	has_one_attached :image

end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :orders
	has_many :questionnaires
	
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :store
	belongs_to :customer
	has_many :orderdetails
end

app/models/orderdetail.rb
class Orderdetail < ApplicationRecord
	has_many :books
	has_many :orders
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
	belongs_to :customer
end

app/models/storage.rb
class Storage < ApplicationRecord
	has_many :stores
	has_many :books
end

app/models/store.rb
class Store < ApplicationRecord
	has_many :orders
	has_many :storages
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:isbn, :title, :author, :pubcom, :price, :body, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def user
  end

  def dataview
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end


  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:order_id, :store_id, :customer_id , :transdate)
    end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]

  # GET /stores or /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to store_url(@store), notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to store_url(@store), notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:storeid, :storename, :mail, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orderdetails_helper.rb
module OrderdetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/helpers/storages_helper.rb
module StoragesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/home/_header.html.erb
<style type="text/css">
  .dropdown:hover .dropdown-menu {
  display: block;
}
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Y書店データベースシステム', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle px-3" id="custdrop" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            顧客
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to 'データ表示', customers_path, class:"dropdown-item" %>
            </li>
            <li>
              <%= link_to 'データ登録', new_customer_path, class:"dropdown-item" %>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle px-3" id="storedrop"href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            店舗
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to 'データ表示', stores_path, class:"dropdown-item" %>
            </li>
            <li>
              <%= link_to 'データ登録', new_store_path, class:"dropdown-item" %>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle px-3" id="storedrop"href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            書籍
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to 'データ表示', books_path, class:"dropdown-item" %>
            </li>
            <li>
              <%= link_to 'データ登録', new_book_path, class:"dropdown-item" %>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle px-3" id="storedrop"href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            在庫
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to 'データ表示', storages_path, class:"dropdown-item" %>
            </li>
            <li>
              <%= link_to 'データ登録', new_storage_path, class:"dropdown-item" %>
          </ul>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle px-3" id="custdrop" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            注文
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to 'データ表示', orders_path, class:"dropdown-item" %>
            </li>
            <li>
              <%= link_to 'データ登録', new_order_path, class:"dropdown-item" %>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to '注文明細', orderdetails_path, class:"dropdown-item" %></li>
            <li><%= link_to '注文明細登録', new_orderdetail_path, class:"dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to '可視化', home_dataview_path, class:"dropdown-item" %></li>
          </ul>
        </li>
      
        <% end %>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'サインオフ', destroy_user_session_path, :method => :delete, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'ユーザー編集', edit_user_registration_path, class:"nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to '新規登録', new_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'サインイン', new_user_session_path, class:"nav-link" %>
        </li>
        <% end %>
        <!--
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    -->
    </div>
  </div>
</nav>

app/views/home/dataview.html.erb
<%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>

<div class="card">
  <div class="card-body">
    <div style:"margin:auto; text-alignment:center">
<%= line_chart Order.group_by_day(:transdate).sum(:money), width: "1000px", height: "600px", xtitle: "日付", ytitle: "売上" %>
</div>
  </div>
</div>

<br>

<div class="card">
  <div class="card-body">
    <div style:"margin:auto; text-alignment:center">
<%= line_chart Order.group_by_day(:transdate).count(:order_id), width: "1000px", height: "600px", xtitle: "日付", ytitle: "注文数" %>
</div>
  </div>
</div>

app/views/home/index.html.erb
<div style="margin:auto;text-align:center;">
<h1>Y書店</h1>
<div>

app/views/home/user.html.erb
<h1>ユーザー</h1>
<p></p>