config/routes.rb
Rails.application.routes.draw do
  resources :questionnaires
  resources :orderdetails
  resources :storages
  resources :books
  resources :orders
  resources :stores
  devise_for :users
  resources :customers
  #get 'home/index'
  get 'home/user'
  get 'home/dataview'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
	belongs_to :customer
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :set_questionnaire, only: %i[ show edit update destroy ]

  # GET /questionnaires or /questionnaires.json
  def index
    @questionnaires = Questionnaire.all
  end

  # GET /questionnaires/1 or /questionnaires/1.json
  def show
  end

  # GET /questionnaires/new
  def new
    @questionnaire = Questionnaire.new
  end

  # GET /questionnaires/1/edit
  def edit
  end

  # POST /questionnaires or /questionnaires.json
  def create
    @questionnaire = Questionnaire.new(questionnaire_params)

    respond_to do |format|
      if @questionnaire.save
        format.html { redirect_to questionnaire_url(@questionnaire), notice: "Questionnaire was successfully created." }
        format.json { render :show, status: :created, location: @questionnaire }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questionnaires/1 or /questionnaires/1.json
  def update
    respond_to do |format|
      if @questionnaire.update(questionnaire_params)
        format.html { redirect_to questionnaire_url(@questionnaire), notice: "Questionnaire was successfully updated." }
        format.json { render :show, status: :ok, location: @questionnaire }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionnaires/1 or /questionnaires/1.json
  def destroy
    @questionnaire.destroy

    respond_to do |format|
      format.html { redirect_to questionnaires_url, notice: "Questionnaire was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def questionnaire_params
      params.require(:questionnaire).permit(:content)
    end
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/views/questionnaires/_form.html.erb
<%= form_with(model: questionnaire) do |form| %>
  <% if questionnaire.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(questionnaire.errors.count, "error") %> prohibited this questionnaire from being saved:</h2>

      <ul>
        <% questionnaire.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/questionnaires/_questionnaire.html.erb
<div id="<%= dom_id questionnaire %>">
  <p>
    <strong>Content:</strong>
    <%= questionnaire.content %>
  </p>

</div>

app/views/questionnaires/edit.html.erb
<h1>Editing questionnaire</h1>

<%= render "form", questionnaire: @questionnaire %>

<br>

<div>
  <%= link_to "Show this questionnaire", @questionnaire %> |
  <%= link_to "Back to questionnaires", questionnaires_path %>
</div>

app/views/questionnaires/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Questionnaires</h1>

<div id="questionnaires">
  <% @questionnaires.each do |questionnaire| %>
    <%= render questionnaire %>
    <p>
      <%= link_to "Show this questionnaire", questionnaire %>
    </p>
  <% end %>
</div>

<%= link_to "New questionnaire", new_questionnaire_path %>

app/views/questionnaires/new.html.erb
<h1>New questionnaire</h1>

<%= render "form", questionnaire: @questionnaire %>

<br>

<div>
  <%= link_to "Back to questionnaires", questionnaires_path %>
</div>

app/views/questionnaires/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @questionnaire %>

<div>
  <%= link_to "Edit this questionnaire", edit_questionnaire_path(@questionnaire) %> |
  <%= link_to "Back to questionnaires", questionnaires_path %>

  <%= button_to "Destroy this questionnaire", @questionnaire, method: :delete %>
</div>